version: '3.8'

services:
  pdftranslate-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: pdftranslate-mcp-server:latest
    container_name: pdftranslate-mcp-server
    restart: unless-stopped
    ports:
      - "8006:8006"
    environment:
      # OpenAI API配置 (必填)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-deepseek-ai/DeepSeek-V3}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.siliconflow.cn/v1}
      
      # MCP服务器配置
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8006
      
      # 翻译配置
      - DEFAULT_LANG_IN=${DEFAULT_LANG_IN:-en}
      - DEFAULT_LANG_OUT=${DEFAULT_LANG_OUT:-zh}
      - QPS=${QPS:-4}
      - WATERMARK_OUTPUT_MODE=${WATERMARK_OUTPUT_MODE:-no_watermark}
      - NO_DUAL=${NO_DUAL:-false}
      - NO_MONO=${NO_MONO:-false}
      
      # 腾讯云COS配置 (可选，用于文件上传)
      - COS_REGION=${COS_REGION}
      - COS_SECRET_ID=${COS_SECRET_ID}
      - COS_SECRET_KEY=${COS_SECRET_KEY}
      - COS_BUCKET=${COS_BUCKET}
      
      # 日志配置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    
    volumes:
      # 挂载配置文件 (可选)
      - ./config.ini:/app/config.ini:ro
      # 挂载日志目录
      - ./logs:/app/logs
      # 挂载临时文件目录
      - ./temp:/app/temp
      # 挂载上传下载目录
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    networks:
      - pdftranslate-network

networks:
  pdftranslate-network:
    driver: bridge